name: Maven integration testing, package and publish Docker image

on:
  push:
    branches:
      - 'main'
      - 'ci/**'

jobs:
  maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -B clean package verify --file pom.xml

      - name: Upload artifact for Docker
        uses: actions/upload-artifact@v3
        with:
          name: java-opthw-app
          path: '${{ github.workspace }}/target/*.jar'

  docker:
    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from Maven job
        uses: actions/download-artifact@v3
        with:
          name: java-opthw-app
      - name: Logging into Docker
        run: docker login ghcr.io -u kenyeresgeza -p ${{ github.token }}
      - name: Build Docker image
        run: docker build . --tag ghcr.io/kenyeresgeza/cubix/1/optional/app:springboot
      - name: Publishing Docker image
        run: docker push ghcr.io/kenyeresgeza/cubix/1/optional/app:springboot
